<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Tag>
 */
class TagFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {

        $seedingTags = [
            'Electricity',
            'Plumbing',
            'Carpentry',
            'Painting',
            'Cleaning',
            'Gardening',
            'Pest Control',
            'HVAC',
            'Moving & Delivery',
            'Tutoring',
            'Auto Repair',
            'IT & Tech Support',
            'Home Renovation',
            'General Handyman',
            'Babysitting',
            'Pet Care',
            'Security Services',
            'Event Planning',
            'Photography',
            'Personal Training',
            'Beauty Services',
            'Massage Therapy',
            'Catering',
            'Legal Services',
            'Financial Services',
            'Real Estate Services',
            'Marketing Services',
            'Web Design',
            'Social Media Management',
            'SEO Services',
            'Content Creation',
            'Video Editing',
            'Interior Design',
            'Landscaping',
            'Roofing',
            'Window Cleaning',
            'Appliance Repair',
            'Electrical Installation',
            'Waterproofing',
            'Home Staging',
            'Elderly Care',
            'Chauffeur Services',
            'Language Translation',
            'Fitness Coaching',
            'Yoga Instruction',
            'Music Lessons',
            'Dance Lessons',
            'Cooking Lessons',
            'Nutrition Coaching',
            'Life Coaching',
            'Career Coaching',
            'Business Coaching',
            'Personal Styling',
            'Personal Shopping',
            'Home Organization',
            'Graphic Design',
            'Copywriting',
            'Voice Over',
            'Virtual Assistance',
            'Data Entry',
            'Customer Support',
            'Project Management',
            'Software Development',
            'App Development',
            'Game Development',
            'Database Management',
            'Network Administration',
            'Cybersecurity',
            'Cloud Computing',
            'AI & Machine Learning',
            'Blockchain Development',
            '3D Modeling',
            'Animation',
            'Augmented Reality',
            'Virtual Reality',
            'Drone Services',
            '3D Printing',
            'Prototyping',
            'Product Design',
            'Market Research',
            'Branding',
            'Public Relations',
            'Event Management',
            'Fundraising',
            'Grant Writing',
            'Business Plan Writing',
            'Financial Planning',
            'Tax Preparation',
            'Bookkeeping',
            'Payroll Services',
            'HR Consulting',
            'Recruitment',
            'Employee Training',
            'Legal Consulting',
            'Patent Services',
            'Trademark Services',
            'Contract Drafting',
            'Mediation Services',
            'Arbitration Services',
            'Litigation Support',
            'Estate Planning',
            'Will Writing',
            'Probate Services',
            'Elder Law',
            'Family Law',
            'Immigration Law',
            'Criminal Defense',
            'Personal Injury',
            'Real Estate Law',
            'Environmental Law',
            'Intellectual Property Law',
            'Corporate Law',
            'Employment Law',
            'Construction Law',
            'Insurance Law',
            'Bankruptcy Law',
            'Entertainment Law',
            'Sports Law',
            'Education Law',
            'Health Law',
            'International Law',
            'Military Law',
            'Admiralty Law',
            'Aviation Law',
            'Space Law',
            'Animal Law',
            'Agricultural Law',
            'Cannabis Law',
            'Energy Law',
            'Telecommunications Law',
            'Transportation Law',
            'Utilities Law',
            'Water Law',
            'Zoning Law',
            'Municipal Law',
            'Election Law',
            'Civil Rights Law',
            'Human Rights Law',
            'Nonprofit Law',
            'Religious Law',
            'Tax Law',
            'Trusts & Estates',
            'Wealth Management',
            'Investment Advisory',
            'Retirement Planning',
            'Insurance Advisory',
            'Risk Management',
            'Compliance Consulting',
            'Forensic Accounting',
            'Fraud Examination',
            'Internal Auditing',
            'External Auditing',
            'IT Auditing',
            'Operational Auditing',
            'Performance Auditing',
            'Quality Assurance',
            'Regulatory Affairs',
            'Clinical Trials',
            'Pharmacovigilance',
            'Medical Writing',
            'Medical Coding',
            'Medical Billing',
            'Healthcare Consulting',
            'Telemedicine',
            'Home Health Care',
            'Nursing Services',
            'Physical Therapy',
            'Occupational Therapy',
            'Speech Therapy',
            'Mental Health Counseling',
            'Substance Abuse Counseling',
            'Marriage Counseling',
            'Family Therapy',
            'Child Therapy',
            'Geriatric Care',
            'Hospice Care',
            'Palliative Care',
            'Rehabilitation Services',
            'Chiropractic Services',
            'Acupuncture',
            'Herbal Medicine',
            'Naturopathy',
            'Homeopathy',
            'Ayurveda',
            'Traditional Chinese Medicine',
            'Functional Medicine',
            'Integrative Medicine',
            'Holistic Health',
            'Wellness Coaching',
            'Health Coaching',
            'Fitness Training',
            'Yoga Instruction',
            'Pilates Instruction',
            'Meditation Instruction',
            'Mindfulness Coaching',
            'Life Coaching',
            'Career Coaching',
            'Executive Coaching',
            'Business Coaching',
            'Leadership Coaching',
            'Team Building',
            'Conflict Resolution',
            'Organizational Development',
            'Change Management',
            'Strategic Planning',
            'Performance Management',
            'Succession Planning',
            'Talent Management',
            'Employee Engagement',
            'Diversity & Inclusion',
            'Corporate Social Responsibility',
            'Sustainability Consulting',
            'Environmental Consulting',
            'Energy Consulting',
            'Waste Management',
            'Recycling Services',
            'Water Treatment',
            'Air Quality Testing',
            'Soil Testing',
            'Environmental Impact Assessment',
            'Environmental Auditing',
            'Environmental Compliance',
            'Environmental Remediation',
            'Hazardous Waste Management',
            'Occupational Health & Safety',
            'Industrial Hygiene',
            'Ergonomics',
            'Safety Training',
            'Emergency Management',
            'Disaster Recovery',
            'Business Continuity',
            'Crisis Management',
            'Risk Assessment',
            'Security Consulting',
            'Cybersecurity Consulting',
            'Penetration Testing',
            'Vulnerability Assessment',
            'Incident Response',
            'Digital Forensics',
            'Security Awareness Training',
            'Security Policy Development',
            'Security Architecture',
            'Security Operations',
            'Security Engineering',
            'Security Management',
            'Security Compliance',
            'Security Auditing',
            'Security Testing',
            'Security Monitoring',
            'Security Analytics',
            'Security Automation',
            'Security Orchestration',
            'Security Incident Management',
            'Security Threat Intelligence',
            'Security Risk Management',
            'Security Governance',
            'Security Strategy',
            'Security Program Development',
            'Security Program Management',
            'Security Metrics',
            'Security Reporting',
            'Security Communication',
            'Security Training',
            'Security Awareness',
            'Security Culture',
            'Security Leadership',
            'Security Innovation',
            'Security Research',
            'Security Development',
            'Security Operations Center'
        ];



        return [
            'name' => fake()->unique()->randomElement($seedingTags),
        ];
    }
}
